### ISSUE TITLE
Cannot find module './sass'

### ISSUE THREAD

**Issue by joelarson4** [jsbin/jsbin#2185]
When attempting to use Sass (that is, change the style editor to "Sass with Compass"), I see an error in my browser console

    scss processor compilation failed
    Internal Server Error Error: Internal Server Error

and in the server log I get this:

    module.js:340
        throw err;
              ^
    Error: Cannot find module './sass'
        at Function.Module._resolveFilename (module.js:338:15)
        at Function.Module._load (module.js:280:25)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at process.<anonymous> (/Users/larsonj/apps/jsbinUpdate/runnablejsbin.3.22.4/lib/processors/index.js:81:21)
        at process.EventEmitter.emit (events.js:98:17)
        at handleMessage (child_process.js:318:10)
        at Pipe.channel.onread (child_process.js:345:11)
    { ouput: { result: '', errors: null },
      error: [Error: Could not parse response from] }

Same thing for SCSS.

I originally reproduced this on 3.22.4 (a0d3ebc020f8a9c9af04911fa9ad6471b83c83e1).  I'm updating to latest to check if it's an issue there.

**Comment by pjanaya** [comment]
Hi guys. I've been trying to install Pennyworth to support SCSS in my local installation of JS Bin. I can't find documentation about that and I don't know how to configure one to talk with the other one. Could someone help me a bit with this? Thank you!

**Comment by remy** [comment]
I think you're sorted with the answer in the Pennyworth repo.
