### ISSUE TITLE
Weird issue with archive

### ISSUE THREAD

**Issue by allouis** [jsbin/jsbin#2228]
I couldn't replicate this with any other bin, but here goes.

visit [this bin (bepabu)](http://jsbin.com/bepabu/1/edit?html,js,output) and you'll notice the file menu has the unarchive option (if you click it it will do nothing as it is not yours) if you then type in the bin, it will create a new bin and the url will update, but the file menu will fail to.

I tried this both logged in and out and it was an issue.

I also tried to replicate by creating a bin, archiving it, and then editing it in an incognito window, but when it created the new bin the whole page refreshed, stopping this issue from happening.

This may be nothing, but if you can replicate too, we may wanna think about force refreshing rather than URL update, or just re-render the menu client side

**Comment by peterblazejewicz** [comment]
@allouis 
I've managed to replicate it.  Here is possible explanation.
Open developer console tool to see runtime JavaScript errors.
When this bin is loaded I'm keep seeing this error:
```
 SyntaxError: Unexpected token )
    at http://static.jsbin.com/js/prod/runner-3.25.5.min.js:1:13840
    at http://static.jsbin.com/js/prod/runner-3.25.5.min.js:1:10893
bepabu.js:14 Uncaught SyntaxError: Unexpected token )
```
```
c = Math.sqrt((a * a) + (b * b));
    window.runnerWindow.proxyConsole.log)
    if (c !== c.toFixed())
```
If you modify a bin and this error disappear, the menu is going away as well (for example when page is fully refreshed).

Cheers!

**Comment by remy** [comment]
Is this specific to this particular bin or is it happening on other bins too? (sorry, little disconnected)

**Comment by peterblazejewicz** [comment]
@remy I cannot repeat the problem (and JavaScript error) with my own bins (e.g. similar content + JavaScript code used in bin).
