### ISSUE TITLE
[I've lost access to all my bin] = Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by TWAD** [jsbin/jsbin#2321]
Hi,
i've just want to create a clone of a bin i worked on.
But unfortunetly, i click on "new" instead of "clone", seeing i'm wrong, i want to go back, so i go back and at this moment i just got this error:

Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
    --------------------
    at Protocol._enqueue (/WWW/jsbin-v3.25.22/node_modules/mysql/lib/protocol/Protocol.js:110:26)
    at Protocol.handshake (/WWW/jsbin-v3.25.22/node_modules/mysql/lib/protocol/Protocol.js:42:41)
    at PoolConnection.Connection.connect (/WWW/jsbin-v3.25.22/node_modules/mysql/lib/Connection.js:81:18)
    at Pool.getConnection (/WWW/jsbin-v3.25.22/node_modules/mysql/lib/Pool.js:44:23)
    at Pool.query (/WWW/jsbin-v3.25.22/node_modules/mysql/lib/Pool.js:131:8)
    at MySQL.module.exports.utils.inherit.getBin (/WWW/jsbin-v3.25.22/lib/db/mysql.js:28:21)
    at Store.(anonymous function) [as getBin] (/WWW/jsbin-v3.25.22/lib/store.js:83:26)
    at BinModel.model.load (/WWW/jsbin-v3.25.22/lib/models/bin.js:21:16)
    at BinModel.metricsWrapper [as load] (/WWW/jsbin-v3.25.22/lib/models/bin.js:211:19)
    at module.exports.Observable.extend.loadBin (/WWW/jsbin-v3.25.22/lib/handlers/bin.js:902:18)

The major effect is, now i can't reach none of my bin :(

**Comment by matthiasbayer** [comment]
Hey,

jsbin is currently under maintenance, see #2320

**Comment by TWAD** [comment]
ah you right! thx ;)
