### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by thesabbir** [jsbin/jsbin#2370]
Installation failed os OS X Yosemite:

*Probably problem is with sqlite3 package

``` sh
$ node -v
v0.12.2

$ npm -v
2.9.0

$ npm i -g jsbin

npm WARN deprecated set-immediate@0.1.1: Use `setimmediate` instead

> sqlite3@2.2.7 install /usr/local/lib/node_modules/jsbin/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Command failed: /usr/local/Cellar/node/0.12.2_1/bin/node --eval require('/usr/local/lib/node_modules/jsbin/node_modules/sqlite3/lib/binding/node-v14-darwin-x64/node_sqlite3.node')
dyld: lazy symbol binding failed: Symbol not found: __ZN2v86Object3SetENS_6HandleINS_5ValueEEES3_NS_17PropertyAttributeE
  Referenced from: /usr/local/lib/node_modules/jsbin/node_modules/sqlite3/lib/binding/node-v14-darwin-x64/node_sqlite3.node
  Expected in: dynamic lookup

dyld: Symbol not found: __ZN2v86Object3SetENS_6HandleINS_5ValueEEES3_NS_17PropertyAttributeE
  Referenced from: /usr/local/lib/node_modules/jsbin/node_modules/sqlite3/lib/binding/node-v14-darwin-x64/node_sqlite3.node
  Expected in: dynamic lookup


node-pre-gyp ERR! Testing pre-built binary failed, attempting to source compile
child_process: customFds option is deprecated, use stdio instead.
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3080500/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3080500/sqlite3.o
Release/obj/gen/sqlite-autoconf-3080500/sqlite3.c:8542:26: warning: unused
      variable 'sqlite3one' [-Wunused-const-variable]
SQLITE_PRIVATE const int sqlite3one = 1;
                         ^
1 warning generated.
  LIBTOOL-STATIC Release/sqlite3.a
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
../src/database.cc:134:18: error: no matching member function for call to 'Set'
    args.This()->Set(NanNew("filename"), args[0]->ToString(), ReadOnly);
    ~~~~~~~~~~~~~^~~
/Users/sabbir/.node-gyp/0.12.2/deps/v8/include/v8.h:2112:8: note: candidate
      function not viable: requires 2 arguments, but 3 were provided
  bool Set(Handle<Value> key, Handle<Value> value);
       ^
/Users/sabbir/.node-gyp/0.12.2/deps/v8/include/v8.h:2114:8: note: candidate
      function not viable: requires 2 arguments, but 3 were provided
  bool Set(uint32_t index, Handle<Value> value);
       ^
../src/database.cc:135:18: error: no matching member function for call to 'Set'
    args.This()->Set(NanNew("mode"), NanNew<Integer>(mode), ReadOnly);
    ~~~~~~~~~~~~~^~~
/Users/sabbir/.node-gyp/0.12.2/deps/v8/include/v8.h:2112:8: note: candidate
      function not viable: requires 2 arguments, but 3 were provided
  bool Set(Handle<Value> key, Handle<Value> value);
       ^
/Users/sabbir/.node-gyp/0.12.2/deps/v8/include/v8.h:2114:8: note: candidate
      function not viable: requires 2 arguments, but 3 were provided
  bool Set(uint32_t index, Handle<Value> value);
       ^
2 errors generated.
make: *** [Release/obj.target/node_sqlite3/src/database.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "/usr/local/Cellar/node/0.12.2_1/bin/node" "/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=sqlite3" "--configuration=Release" "--module_name=node_sqlite3" "--version=2.2.7" "--major=2" "--minor=2" "--patch=7" "--runtime=node" "--node_abi=node-v14" "--platform=darwin" "--target_platform=darwin" "--arch=x64" "--target_arch=x64" "--module_main=./lib/sqlite3" "--host=https://mapbox-node-binary.s3.amazonaws.com/" "--module_path=/usr/local/lib/node_modules/jsbin/node_modules/sqlite3/lib/binding/node-v14-darwin-x64" "--remote_path=./sqlite3/v2.2.7/" "--package_name=node-v14-darwin-x64.tar.gz" "--staged_tarball=build/stage/sqlite3/v2.2.7/node-v14-darwin-x64.tar.gz" "--hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/" "--hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/node-v14-darwin-x64.tar.gz"
gyp ERR! cwd /usr/local/lib/node_modules/jsbin/node_modules/sqlite3
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/0.12.2_1/bin/node rebuild --name=sqlite3 --configuration=Release --module_name=node_sqlite3 --version=2.2.7 --major=2 --minor=2 --patch=7 --runtime=node --node_abi=node-v14 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=./lib/sqlite3 --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=/usr/local/lib/node_modules/jsbin/node_modules/sqlite3/lib/binding/node-v14-darwin-x64 --remote_path=./sqlite3/v2.2.7/ --package_name=node-v14-darwin-x64.tar.gz --staged_tarball=build/stage/sqlite3/v2.2.7/node-v14-darwin-x64.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/node-v14-darwin-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/jsbin/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
node-pre-gyp ERR! System Darwin 14.3.0
node-pre-gyp ERR! command "node" "/usr/local/lib/node_modules/jsbin/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/jsbin/node_modules/sqlite3
node-pre-gyp ERR! node -v v0.12.2
node-pre-gyp ERR! node-pre-gyp -v v0.5.22
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/Cellar/node/0.12.2_1/bin/node rebuild --name=sqlite3 --configuration=Release --module_name=node_sqlite3 --version=2.2.7 --major=2 --minor=2 --patch=7 --runtime=node --node_abi=node-v14 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=./lib/sqlite3 --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=/usr/local/lib/node_modules/jsbin/node_modules/sqlite3/lib/binding/node-v14-darwin-x64 --remote_path=./sqlite3/v2.2.7/ --package_name=node-v14-darwin-x64.tar.gz --staged_tarball=build/stage/sqlite3/v2.2.7/node-v14-darwin-x64.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/node-v14-darwin-x64.tar.gz' (1)
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "i" "-g" "jsbin"
npm ERR! node v0.12.2
npm ERR! npm  v2.9.0
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@2.2.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@2.2.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sabbir/npm-debug.log
```

**Comment by LongLiveCHIEF** [comment]
+1

**Comment by flamingtop** [comment]
Same here.

**Comment by flamingtop** [comment]
Downgraded node to 0.10.38 then did npm update -g && npm install -g jsbin, works for me.

**Comment by remy** [comment]
Just as a heads up, node 0.12 is not supported (in production and dev I'm
running 0.10, and have no short term plans to upgrade.

Happy to accept a PR that lands 0.12 support (so long as its not at the
expense of 0.10).

**Comment by flamingtop** [comment]
Hi @remy Could you point me to the latest documentation for setting up jsbin behind nginx (without varnish)? Although downgrading node helped me get it running, I'm still getting 400 errors on /login, /save ajax calls. I found if I register as a new user I got immediately signed in but /save gave 400. If I log out and try to relogin with my existing email/password, /login gave me 400. I wonder if I  got the set up right. Thanks.

**Comment by hartman** [comment]
Anyone got a workaround for those of us who cannot downgrade ?

**Comment by remy** [comment]
Downgrade from node 0.12?

Two workarounds:

1. PR the project to get compatibility
2. Use nvm to drop into node 0.10.x

I'm sticking to using 0.10 in production until there's a good reason to
move, which is why I've not noticed the 0.12 issues. Sorry!

**Comment by chrisbolin** [comment]
I realize this issue is old, but it's still relevant, so I thought I'd update the docs: https://github.com/jsbin/learn/pull/78
