### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by ufoe** [jsbin/jsbin#2451]
localhost:jsbin guiyin$ npm install -g jsbin
npm WARN deprecated set-immediate@0.1.1: Use `setimmediate` instead

> sqlite3@2.2.7 install /usr/local/lib/node_modules/jsbin/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Command failed: /usr/local/bin/node --eval require('/usr/local/lib/node_modules/jsbin/node_modules/sqlite3/lib/binding/node-v14-darwin-x64/node_sqlite3.node')
dyld: lazy symbol binding failed: Symbol not found: __ZN2v86Object3SetENS_6HandleINS_5ValueEEES3_NS_17PropertyAttributeE
  Referenced from: /usr/local/lib/node_modules/jsbin/node_modules/sqlite3/lib/binding/node-v14-darwin-x64/node_sqlite3.node
  Expected in: dynamic lookup

dyld: Symbol not found: __ZN2v86Object3SetENS_6HandleINS_5ValueEEES3_NS_17PropertyAttributeE
  Referenced from: /usr/local/lib/node_modules/jsbin/node_modules/sqlite3/lib/binding/node-v14-darwin-x64/node_sqlite3.node
  Expected in: dynamic lookup

node-pre-gyp ERR! Testing pre-built binary failed, attempting to source compile
child_process: customFds option is deprecated, use stdio instead.
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3080500/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3080500/sqlite3.o
Release/obj/gen/sqlite-autoconf-3080500/sqlite3.c:8542:26: warning: unused variable 'sqlite3one' [-Wunused-const-variable]
SQLITE_PRIVATE const int sqlite3one = 1;
                         ^
1 warning generated.
  LIBTOOL-STATIC Release/sqlite3.a
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
../src/database.cc:134:18: error: no matching member function for call to 'Set'
    args.This()->Set(NanNew("filename"), args[0]->ToString(), ReadOnly);
    ~~~~~~~~~~~~~^~~
/Users/guiyin/.node-gyp/0.12.5/deps/v8/include/v8.h:2112:8: note: candidate function not viable: requires 2 arguments, but 3 were provided
  bool Set(Handle<Value> key, Handle<Value> value);
       ^
/Users/guiyin/.node-gyp/0.12.5/deps/v8/include/v8.h:2114:8: note: candidate function not viable: requires 2 arguments, but 3 were provided
  bool Set(uint32_t index, Handle<Value> value);
       ^
../src/database.cc:135:18: error: no matching member function for call to 'Set'
    args.This()->Set(NanNew("mode"), NanNew<Integer>(mode), ReadOnly);
    ~~~~~~~~~~~~~^~~
/Users/guiyin/.node-gyp/0.12.5/deps/v8/include/v8.h:2112:8: note: candidate function not viable: requires 2 arguments, but 3 were provided
  bool Set(Handle<Value> key, Handle<Value> value);
       ^
/Users/guiyin/.node-gyp/0.12.5/deps/v8/include/v8.h:2114:8: note: candidate function not viable: requires 2 arguments, but 3 were provided
  bool Set(uint32_t index, Handle<Value> value);
       ^
2 errors generated.
make: **\* [Release/obj.target/node_sqlite3/src/database.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=sqlite3" "--configuration=Release" "--module_name=node_sqlite3" "--version=2.2.7" "--major=2" "--minor=2" "--patch=7" "--runtime=node" "--node_abi=node-v14" "--platform=darwin" "--target_platform=darwin" "--arch=x64" "--target_arch=x64" "--module_main=./lib/sqlite3" "--host=https://mapbox-node-binary.s3.amazonaws.com/" "--module_path=/usr/local/lib/node_modules/jsbin/node_modules/sqlite3/lib/binding/node-v14-darwin-x64" "--remote_path=./sqlite3/v2.2.7/" "--package_name=node-v14-darwin-x64.tar.gz" "--staged_tarball=build/stage/sqlite3/v2.2.7/node-v14-darwin-x64.tar.gz" "--hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/" "--hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/node-v14-darwin-x64.tar.gz"
gyp ERR! cwd /usr/local/lib/node_modules/jsbin/node_modules/sqlite3
gyp ERR! node -v v0.12.5
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node rebuild --name=sqlite3 --configuration=Release --module_name=node_sqlite3 --version=2.2.7 --major=2 --minor=2 --patch=7 --runtime=node --node_abi=node-v14 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=./lib/sqlite3 --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=/usr/local/lib/node_modules/jsbin/node_modules/sqlite3/lib/binding/node-v14-darwin-x64 --remote_path=./sqlite3/v2.2.7/ --package_name=node-v14-darwin-x64.tar.gz --staged_tarball=build/stage/sqlite3/v2.2.7/node-v14-darwin-x64.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/node-v14-darwin-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/jsbin/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
node-pre-gyp ERR! System Darwin 14.3.0
node-pre-gyp ERR! command "node" "/usr/local/lib/node_modules/jsbin/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/jsbin/node_modules/sqlite3
node-pre-gyp ERR! node -v v0.12.5
node-pre-gyp ERR! node-pre-gyp -v v0.5.22
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node rebuild --name=sqlite3 --configuration=Release --module_name=node_sqlite3 --version=2.2.7 --major=2 --minor=2 --patch=7 --runtime=node --node_abi=node-v14 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=./lib/sqlite3 --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=/usr/local/lib/node_modules/jsbin/node_modules/sqlite3/lib/binding/node-v14-darwin-x64 --remote_path=./sqlite3/v2.2.7/ --package_name=node-v14-darwin-x64.tar.gz --staged_tarball=build/stage/sqlite3/v2.2.7/node-v14-darwin-x64.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/node-v14-darwin-x64.tar.gz' (1)
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "jsbin"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@2.2.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@2.2.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Library/WebServer/Documents/jsbin/npm-debug.log

**Comment by remy** [comment]
As much as I enjoyed reading through your massive log dump, and it's likely that I won't be able to fix any of this, any chance of sharing the most useful bit of info: what version of node + npm are you using?

node 0.12 isn't supported, nor is io.js.

**Comment by Ridlsan** [comment]
@remy Just downloaded latest version of Node.js ( 0.12.6)  and the same error. (windows 8.1)
What do u mean by "node 0.12 isn't supported"?

**Comment by remy** [comment]
I mean I've never run jsbin with 0.12 and if you run into problems you're
on your own and welcome you send PRs that are 100% compatible with 0.10.

**Comment by ufoe** [comment]
@remy thank you. i will try node 0.10 later.
