### ISSUE TITLE
Local jsbin getting down behind nginx https proxy 

### ISSUE THREAD

**Issue by someanon** [jsbin/jsbin#2733]
Doing everything according https://github.com/jsbin/jsbin/blob/master/docs/nginx-config.md i'm getting error:

```
TypeError: Cannot call method 'indexOf' of undefined
    at Object.module.exports.protocolCheck [as handle] (/usr/local/lib/node_modules/jsbin/lib/middleware.js:267:34)
    at next (/usr/local/lib/node_modules/jsbin/node_modules/express/node_modules/connect/lib/proto.js:199:15)
    at Object.handle (/usr/local/lib/node_modules/jsbin/lib/middleware.js:90:7)
    at next (/usr/local/lib/node_modules/jsbin/node_modules/express/node_modules/connect/lib/proto.js:199:15)
    at Object.handle (/usr/local/lib/node_modules/jsbin/lib/middleware.js:28:7)
    at next (/usr/local/lib/node_modules/jsbin/node_modules/express/node_modules/connect/lib/proto.js:199:15)
    at Object.handle (/usr/local/lib/node_modules/jsbin/lib/middleware.js:61:9)
    at next (/usr/local/lib/node_modules/jsbin/node_modules/express/node_modules/connect/lib/proto.js:199:15)
    at Object.handle (/usr/local/lib/node_modules/jsbin/lib/middleware.js:41:7)
    at next (/usr/local/lib/node_modules/jsbin/node_modules/express/node_modules/connect/lib/proto.js:199:15)
    at Object.handle (/usr/local/lib/node_modules/jsbin/lib/middleware.js:100:7)
    at next (/usr/local/lib/node_modules/jsbin/node_modules/express/node_modules/connect/lib/proto.js:199:15)
    at Object.handle (/usr/local/lib/node_modules/jsbin/lib/middleware.js:150:7)
    at next (/usr/local/lib/node_modules/jsbin/node_modules/express/node_modules/connect/lib/proto.js:199:15)
    at Object.handle (/usr/local/lib/node_modules/jsbin/lib/middleware.js:252:9)
    at next (/usr/local/lib/node_modules/jsbin/node_modules/express/node_modules/connect/lib/proto.js:199:15)
    at /usr/local/lib/node_modules/jsbin/node_modules/express/node_modules/connect/lib/middleware/csrf.js:48:88
    at Object.handle (/usr/local/lib/node_modules/jsbin/lib/middleware.js:111:16)
    at next (/usr/local/lib/node_modules/jsbin/node_modules/express/node_modules/connect/lib/proto.js:199:15)
    at Object.json [as handle] (/usr/local/lib/node_modules/jsbin/node_modules/express/node_modules/connect/lib/middleware/json.js:53:37)
    at next (/usr/local/lib/node_modules/jsbin/node_modules/express/node_modules/connect/lib/proto.js:199:15)
    at Object.urlencoded [as handle] (/usr/local/lib/node_modules/jsbin/node_modules/express/node_modules/connect/lib/middleware/urlencoded.js:51:37)
    at next (/usr/local/lib/node_modules/jsbin/node_modules/express/node_modules/connect/lib/proto.js:199:15)
    at Object.cookieSession [as handle] (/usr/local/lib/node_modules/jsbin/node_modules/express/node_modules/connect/lib/middleware/cookieSession.js:113:5)
    at next (/usr/local/lib/node_modules/jsbin/node_modules/express/node_modules/connect/lib/proto.js:199:15)
    at Object.cookieParser [as handle] (/usr/local/lib/node_modules/jsbin/node_modules/express/node_modules/connect/lib/middleware/cookieParser.js:60:5)
    at next (/usr/local/lib/node_modules/jsbin/node_modules/express/node_modules/connect/lib/proto.js:199:15)
    at Object.handle (/usr/local/lib/node_modules/jsbin/lib/middleware.js:190:7)
    at next (/usr/local/lib/node_modules/jsbin/node_modules/express/node_modules/connect/lib/proto.js:199:15)
    at resume (/usr/local/lib/node_modules/jsbin/node_modules/express/node_modules/connect/lib/middleware/static.js:60:7)
    at SendStream.error (/usr/local/lib/node_modules/jsbin/node_modules/express/node_modules/connect/lib/middleware/static.js:73:37)
    at SendStream.emit (events.js:95:17)
    at SendStream.error (/usr/local/lib/node_modules/jsbin/node_modules/express/node_modules/send/lib/send.js:147:51)
    at SendStream.onStatError (/usr/local/lib/node_modules/jsbin/node_modules/express/node_modules/send/lib/send.js:248:48)
    at /usr/local/lib/node_modules/jsbin/node_modules/express/node_modules/send/lib/send.js:320:26
    at Object.oncomplete (fs.js:108:15)
```

My jsbin config: 

```
{
  "url": {
    "host": "<host>",
    "prefix": "/",
    "ssl": true 
  },
  "store": {
    "adapter": "sqlite",
    "sqlite": {
      "location": "<db-file-path>"
    }
  }
}
```

Starting jsbin as:
`JSBIN_PROXY=on PORT=3000 jsbin -c /etc/jsbin.conf.json`

**Comment by kodi** [comment]
version on NPM is ancient,

https://www.npmjs.com/package/jsbin

i used one docker image which used global install, it just didn't work. After that we switched to another that used more recent branch from github, this now works, and you can set ssl  to true.

checkout code from github, and build using npm install -d, go into bin folder and start it.

(also use nodeenv or n to run it with old node, 0.10.46 works for me)

**Comment by remy** [comment]
I can confirm all the things @kodi said are true :)
