### ISSUE TITLE
This string literal causes error: "*for"

### ISSUE THREAD

**Issue by robin-a-meade** [jsbin/jsbin#2797]
```javascript
var s   = "*for";`
```

```
"error"
"SyntaxError: Unexpected token {
    at https://static.jsbin.com/js/prod/runner-3.36.9.min.js:1:13891
    at https://static.jsbin.com/js/prod/runner-3.36.9.min.js:1:10820"
```

Same for  `*do` and `*while`

http://jsbin.com/seqihubiqo/edit?js,console

**Comment by remy** [comment]
Can you add a comment that reads `// noprotect`
