### ISSUE TITLE
Throws syntax error when 'do' keyword is in string

### ISSUE THREAD

**Issue by technoknol** [jsbin/jsbin#2851]
[Look at this bin, ](http://jsbin.com/zawofigito/1/edit?html,js,console,output)

there is just one simple line 
`document.getElementById('abc').innerHTML = 'this is abc do ';`

And it throws an syntax error. 
Escaping `o` will remove the error, Strange !!!

## Error 

```
"SyntaxError: Unexpected token {
    at https://static.jsbin.com/js/prod/runner-3.39.11.min.js:1:13926
    at https://static.jsbin.com/js/prod/runner-3.39.11.min.js:1:10855"

```

**Comment by technoknol** [comment]
Closing this issue, as this is similar to issue [2264](https://github.com/jsbin/jsbin/issues/2264), and there is work around also. but not fixed yet.
