### ISSUE TITLE
Extended Class doesn't init in Event  - Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by happierall** [jsbin/jsbin#2906]
[Bin link](http://jsbin.com/vixoko/1/edit?js,console,output)
Code

``` javascript
/*jshint esnext: true */

class Shape {
  constructor() {
    console.log("Init Shape")
  }
}

class Circle extends Shape {
  constructor() {
    super()
    console.log("Init Circle")
  }
}

// It's ok
var circle = new Circle()

window.addEventListener("click", () => {
  // It's not ok
  var circle = new Circle()
})
```

Error:

```
"TypeError: Cannot read property 'call' of undefined
    at new Circle (vixoko.js:25:71)
    at vixoko.js:36:16"
```

**Comment by happierall** [comment]
Huh, day  after already work...

**Comment by happierall** [comment]
Doesn't work with babel. (Not forget click on area)
