### ISSUE TITLE
Console reporting "a.split is not a function" regardless of input

### ISSUE THREAD

**Issue by ianboucher** [jsbin/jsbin#3010]
For the last two days the console reports:
```
TypeError: a.split is not a function
    at Object.e [as protect]
```

regardless of the code I input to the console / JavaScript windows. None of the code I have written has directly used `a.split()`

[Update: it appears that the error does not occur _regardless_ of the code I input (it works in some cases - see below), but still occurs for a range of inputs without obvious cause]

**Comment by ecaepsey** [comment]
same issues
`function pow(x, n) {
  var i = 1;
  var result = x;
  while(i < n) {
    result *= x;
    ++i;
    
  }
  
  return result;
}

console.log(pow(2,3))
`
wrote this code

**Comment by ianboucher** [comment]
Further info...

Trying out a Codewars solution, the following code resulted in the `a.split()' error:

function findOdd(a) {
  var seen   = {};
  var result = 0;
  
```
  for (var i = 0; i < a.length; i++) {
    if (seen[a[i]]) {
      seen[a[i]] = false;
      result -= a[i];
    }
    else {
      seen[a[i]] = true;
      result += a[i];
    }
  }
  
  return result;
}
```

*But* the following code worked as expected:

```
function getOdd(a) {
  return a.reduce(function(acc, val){
    console.log(acc ^ val);
    return acc ^ val;
  });
}
```

**Comment by benjaminEwhite** [comment]
Experiencing this issue as well.   When jsbin runs this code:

```javascript
function max(numbers) {

  var currentMax = numbers[0];
  for (var i=0; i <= numbers.length; i++) {
    if (numbers[i] > currentMax) {
       currentMax = numbers[i];
    }
  }
  return currentMax;
}


function min(numbers) {
 
  var currentMin = numbers[0];
  for (var i=0; i <= numbers.length; i++) {
    if (numbers[i] < currentMin) {
       currentMin = numbers[i];
    }
  }
  return currentMin;
}


// tests

function testFunctionWorks(fn, input, expected) {
  if (fn(input) === expected) {
    console.log('SUCCESS: `' + fn.name + '` works on `[' + input + ']`');
    return true;
  }
  else {
    console.log(
      'FAILURE: `' + fn.name + '([' + input + '])` should be ' + expected +
      ' but was ' + fn(input)
    );
    return false;
  }
}


(function runTests() {
  // we'll use the variables in our test cases
  var numList1 = [-5, 28, 98, -20013, 0.7878, 22, 115];
  var realMin1 = numList1[3];
  var realMax1 = numList1[6];
  var numList2 = [0, 1, 2, 3, 4];
  var realMin2 = numList2[0];
  var realMax2 = numList2[4];
  
  var testResults = [
    testFunctionWorks(max, numList1, realMax1),
    testFunctionWorks(max, numList2, realMax2),
    testFunctionWorks(min, numList1, realMin1),
    testFunctionWorks(min, numList2, realMin2),
  ];
  
  var numPassing = testResults.filter(function(result){ return result; }).length;
  console.log(numPassing + ' out of ' + testResults.length + ' tests passing.');
})();
```

Get this error:

```
TypeError: a.split is not a function
    at Object.e [as protect] (https://static.jsbin.com/js/prod/runner-3.41.6.min.js:1:5781)
    at max (sahaxi.js:9:24)
    at testFunctionWorks (sahaxi.js:53:7)
    at runTests (sahaxi.js:77:5)
    at sahaxi.js:85:3
    at https://static.jsbin.com/js/prod/runner-3.41.6.min.js:1:13926
    at https://static.jsbin.com/js/prod/runner-3.41.6.min.js:1:10855"
```

Seems to have cropped up in last 24 hours. Also of note, the code works as expected when pasted into dev tools js console, or JSBin's built in console.

**Comment by dojo-json** [comment]
As a workaround, you can add `//noprotect` at the top of your bin.

**Comment by remy** [comment]
I'm getting to the bottom of this, but it looks like jsbin is out of date by about 6 or more feature releases (let alone bugs).

**Comment by remy** [comment]
Should be fixed now. Thanks for reporting.

**Comment by ianboucher** [comment]
Thanks for the hard work and the quick response. Love JS Bin - I was lost without it!
