### ISSUE TITLE
npm install fails on snyk-protect

### ISSUE THREAD

**Issue by stepankuzmin** [jsbin/jsbin#3028]
npm install fails on `snyk-protect` prepublish script with `Set is not defined`

```shell
591 info jsbin@3.41.9 Failed to exec prepublish script
592 verbose stack Error: jsbin@3.41.9 prepublish: `npm run snyk-protect`
592 verbose stack Exit status 1
592 verbose stack     at EventEmitter.<anonymous> (/Users/stepan/.nvm/v0.10.48/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
592 verbose stack     at EventEmitter.emit (events.js:98:17)
592 verbose stack     at ChildProcess.<anonymous> (/Users/stepan/.nvm/v0.10.48/lib/node_modules/npm/lib/utils/spawn.js:24:14)
592 verbose stack     at ChildProcess.emit (events.js:98:17)
592 verbose stack     at maybeClose (child_process.js:766:16)
592 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
```

This is cause for https://github.com/jsbin/jsbin/pull/3019

`node v0.10.48`
jsbin@0c7e6ff514409648db4a8decd98b8d3a82996f5f

**Comment by chinchang** [comment]
I guess it isn't required for working of JSBin. I just removed the script for `prepublish` in package.json (`"prepublish": "npm run snyk-protect",`) and it worked fine then.

**Comment by remy** [comment]
Removed now, so it should installed - or certainly doesn't rely on it.
