### ISSUE TITLE
NOT ABLE TO SAVE

### ISSUE THREAD

**Issue by MillerAppBeta** [jsbin/jsbin#3107]
Cannot save anything, refreshing does not do any good

**Comment by MillerAppBeta** [comment]
POST /kevadew/save
Error
    at BinHandler.validateBin (/WWW/jsbin-v4.0.4/lib/handlers/bin.js:893:10)
    at BinHandler.createBin (/WWW/jsbin-v4.0.4/lib/handlers/bin.js:475:10)
    at BinHandler.createRevisionOrClone (/WWW/jsbin-v4.0.4/lib/handlers/bin.js:512:12)
    at Layer.handle [as handle_request] (/WWW/jsbin-v4.0.4/node_modules/express/lib/router/layer.js:95:5)
    at next (/WWW/jsbin-v4.0.4/node_modules/express/lib/router/route.js:137:13)
    at /WWW/jsbin-v4.0.4/lib/routes.js:39:5
    at Layer.handle [as handle_request] (/WWW/jsbin-v4.0.4/node_modules/express/lib/router/layer.js:95:5)
    at next (/WWW/jsbin-v4.0.4/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/WWW/jsbin-v4.0.4/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/WWW/jsbin-v4.0.4/node_modules/express/lib/router/layer.js:95:5)

**Comment by MillerAppBeta** [comment]
"Blacklisted"

**Comment by MillerAppBeta** [comment]
I have narrowed down the error to window.location.href. Btw, thanks for the great software you provide!

**Comment by MillerAppBeta** [comment]
The cause of the problem was: window.location.href
