### ISSUE TITLE
Fail connecting to Database.

### ISSUE THREAD

**Issue by esdmr** [jsbin/jsbin#3146]
### Fail connecting to Database.

I cant create new users, so I checked the console and saw the ECONNECT error.

#### General Information

+ Running Windows 10 Pro x64, 4 GB ram, 2.5 GHz Cpu.

+ Running JSbin Version [`4.1.0`](https://github.com/jsbin/jsbin/releases/tag/v4.1.0)
  
| Related Deps | Version |
|:---|---:|
|bcrypt-nodejs|0.0.3|
|express|4.16.2|
|grunt|1.0.1|
|grunt-cli|0.1.13|
|grunt-contrib-concat|1.0.1|
|grunt-contrib-jshint|0.1.1|
|grunt-contrib-uglify|2.3.0|
|mysql|2.15.0|

+ Log
```js
Error: connect ECONNREFUSED 127.0.0.1:3306
    at Object._errnoException (util.js:1019:11)
    at _exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)
    --------------------
    at Protocol._enqueue (%userprofile%\Desktop\jsbin-master\jsbin-master\node_modules\mysql\lib\protocol\Protocol.js:145:48)
    at Protocol.handshake (C:\Users\fujitsu\Desktop\jsbin-master\jsbin-master\node_modules\mysql\lib\protocol\Protocol.js:52:23)
    at PoolConnection.connect (%userprofile%\Desktop\jsbin-master\jsbin-master\node_modules\mysql\lib\Connection.js:130:18)
    at Pool.getConnection (%userprofile%\Desktop\jsbin-master\jsbin-master\node_modules\mysql\lib\Pool.js:48:16)
    at Pool.query (%userprofile%\Desktop\jsbin-master\jsbin-master\node_modules\mysql\lib\Pool.js:202:8)
    at MySQL.setUser (%userprofile%\Desktop\jsbin-master\jsbin-master\lib\db\mysql.js:248:21)
    at Store.(anonymous function) [as setUser] (%userprofile%\Desktop\jsbin-master\jsbin-master\lib\store.js:88:26)
    at UserModel.<anonymous> (%userprofile%\Desktop\jsbin-master\jsbin-master\lib\models\user.js:75:13)
    at %userprofile%\Desktop\jsbin-master\jsbin-master\node_modules\bcrypt-nodejs\bCrypt.js:631:3
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
```
 + Options
```js
{
    "store": {
        "adapter": "mysql",
        "sqlite": {
            "location": "jsbin.sqlite"
        },
        "mysql": {
            "host": "localhost",
            "user": "root",
            "password": "",
            "database": "jsbin",
            "charset": "utf8mb4",
            "collate": "utf8mb4_unicode_ci"
        }
    }
}
/*extends config.default.json*/
```
#### Steps To Reproduce

1. Install JSbin with corresponding dependencies and options.
2. After launching the server, try creating an Account.

##### Correct Behavior

The application sends An Welcome Email;
And everything will be fine.

##### Incorrect Behavior

The (Not Fatal) Error broadcasts through the console;
And the page shows an empty yellow message.

**Comment by remy** [comment]
Your database isn't running. It's in the first line of your logs. Can't connect to port 3036 (or whatever it is -replying on mobile)
