### ISSUE TITLE
unable to build locally

### ISSUE THREAD

**Issue by titaniumbones** [jsbin/jsbin#3242]
Hi Remy,
I'm tyring to build a local version of jsbin for an html class in a remote villae in India where we might not have internet.  I've been trying to build jsbin with 
```
nvm use v0.10
npm install
```
but I get a whole lot of package warmings and then a failure message here: 

```
npm ERR! Linux 4.16.0-2-ARCH
npm ERR! argv "/home/matt/.nvm/v0.10.48/bin/node" "/home/matt/.nvm/v0.10.48/bin/npm" "install"
npm ERR! node v0.10.48
npm ERR! npm  v2.15.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package grunt@1.0.2 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer grunt-contrib-concat@1.0.1 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-contrib-jshint@0.1.1 wants grunt@~0.4.0

npm ERR! Please include the following file with any support request:
npm ERR!     /home/matt/src/jsbin-git/npm-debug.log
```

using node 8.11.1, I am able to build (yay!) but I get a fatal error on run: 

```
Config from /home/matt/src/jsbin-git/lib/config.local.json
/home/matt/src/jsbin-git/lib/store.js:5
    throw new Error(`${options.adapter} is not supported, only mysql as of v4.`);
    ^

Error: sqlite is not supported, only mysql as of v4.
    at new Store (/home/matt/src/jsbin-git/lib/store.js:5:11)
    at createStore (/home/matt/src/jsbin-git/lib/store.js:93:10)
    at Object.<anonymous> (/home/matt/src/jsbin-git/lib/app.js:16:37)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)

```

do you have any thoughts? Thank you! 
Matt

**Comment by remy** [comment]
Use node 6 or equally use the v5 branch.

**Comment by titaniumbones** [comment]
ok thx now able to build, will open a new issue for running

**Comment by remy** [comment]
@srujanmelam bottom of this (embarrassingly old) blog post https://jsbin.com/blog/the-return-and-the-refactor/

**Comment by srujanmelam** [comment]
@remy i actually did run it on the port 3000 but the output part of **html,css,js,console,output** is not rendering at all when im writing code in html,css and js. can you please help me with that.
