### ISSUE TITLE
mysql instructions?

### ISSUE THREAD

**Issue by titaniumbones** [jsbin/jsbin#3243]
in branch v4.1.4, using node 6.14.5 or 8.11.14, atempt to run `node .` fails with:

```
 node .
Config from /home/matt/src/jsbin-git/lib/config.local.json
/home/matt/src/jsbin-git/lib/store.js:5
    throw new Error(`${options.adapter} is not supported, only mysql as of v4.`);
    ^

Error: sqlite is not supported, only mysql as of v4.
    at new Store (/home/matt/src/jsbin-git/lib/store.js:5:11)
    at createStore (/home/matt/src/jsbin-git/lib/store.js:93:10)
    at Object.<anonymous> (/home/matt/src/jsbin-git/lib/app.js:16:37)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
```

Are there instructions for using mysql somewhere? thanks!

**Comment by titaniumbones** [comment]
closing, I see i have to change config.local.json to mysql.
